/**
 * A zero knowledge proof program to send a number to a recipient
 * As generated by ChatGPT and then modified
 * is an "interactive" ZKP program
 */
use std::marker::Sized;
use rand::Rng;
use sha2::{Digest, Sha256};

// A trait for types that can be used as commitments in a zero-knowledge proof
trait Commitment: Sized {
    // A method for creating a commitment from a value
    fn commit(value: Self) -> Self;
    // A method for opening a commitment and revealing the value
    fn open(self) -> Option<Self>;
}

// A trait for types that can be used as challenges in a zero-knowledge proof
trait Challenge: Sized {
    // A method for creating a challenge from a commitment
    fn challenge(_commitment: &Self) -> Self;
}

// A trait for types that can be used as responses in a zero-knowledge proof
trait Response: Sized {
    // A method for creating a response from a value and a challenge
    fn respond(value: Self, _challenge: &Self) -> Self;
    // A method for verifying a response given a commitment and challenge
    fn verify(commitment: &Self, challenge: &Self, response: &Self) -> bool;
}

// A struct for holding the commitments, challenges, and responses in a zero-knowledge proof
// struct Proof<C: Commitment, Ch: Challenge, R: Response> {
//     commitment: C,
//     challenge: Ch,
//     response: R,
// }

impl Commitment for u64 {
    fn commit(value: Self) -> Self {
        // Hash the value to create a commitment
        let mut hasher = Sha256::new();
        hasher.update(value.to_le_bytes());
        let hash = hasher.finalize();
        // Return the commitment as a u64
        let mut array = [0u8; 8];
        array.copy_from_slice(&hash[..8]);
        u64::from_le_bytes(array)
    }

    fn open(self) -> Option<Self> {
        // In this implementation, the commitment can always be opened to reveal the value
        Some(self)
    }
}

impl Challenge for u64 {
    fn challenge(_commitment: &Self) -> Self {
        // Generate a random challenge
        rand::thread_rng().gen()
    }
}

impl Response for u64 {
    fn respond(value: Self, _challenge: &Self) -> Self {
        // Calculate the response as a function of the value and challenge
        value % 100 + _challenge % 100
    }

    fn verify(commitment: &Self, challenge: &Self, response: &Self) -> bool {
        // Calculate the expected response based on the commitment and challenge
        let expected_response = Self::respond(*commitment, challenge);
        // Check if the calculated response matches the given response
        // println!("response: {}, expected_response: {}, {}", response, &expected_response, response == &expected_response);

        response == &expected_response
    }
}

fn main() {
    // The number of iterations to perform
    const USE_RANDOM: bool = true;
    let iterations: i32 = 100;

    // The prover knows an even number, but doesn't want to reveal what it is
    let mut value: u64;

    if !USE_RANDOM {
        value = 437567812942;
    } else {
        value = 0;
    }

    // A counter for the number of successful proofs
    let mut successful_proofs = 0;

    for _ in 0..iterations {
        // generate a random number
        if USE_RANDOM {
            value = rand::thread_rng().gen();
        }

        // The prover creates a commitment to the value
        let commitment = u64::commit(value);

        // The verifier creates a challenge based on the commitment
        let challenge = u64::challenge(&commitment);

        // The prover creates a response to the challenge
        // randomize the order of the challenge and value
        let mut rng = rand::thread_rng();

        // let response = u64::respond(challenge, &challenge);
        let response = if rng.gen_range(0..1) == 0 {
            u64::respond(value, &challenge)
        } else {
            u64::respond(challenge, &value)
        };

        // The verifier verifies the response using the commitment and challenge
        if !u64::verify(&commitment, &challenge, &response) {
            successful_proofs += 1;
        }
    }

    // Calculate the probability of a successful proof
    let probability = successful_proofs as f64 / iterations as f64;
    println!("The probability of a successful proof is {:.2}.", probability);

    // if probability is above 0.95 then the challenge is passed
    if probability > 0.95 {
        println!("The proof is valid, the prover knows an even number.");
    } else {
        println!("The proof is invalid, the prover does not know an even number.");
    }
}
